if (DEFINED EXPECTED_SELECTION)
    include("${SELECTION_MODULE}")
    if (NOT AURORA_VITA_RENDERER STREQUAL EXPECTED_SELECTION)
        message(FATAL_ERROR "Unexpected renderer ${AURORA_VITA_RENDERER}")
    endif ()
    get_property(choices CACHE AURORA_VITA_RENDERER PROPERTY STRINGS)
    if (NOT choices STREQUAL "VITAGL;GXM")
        message(FATAL_ERROR "Renderer choices are not exposed to CMake clients")
    endif ()
    return()
endif ()

foreach (selection IN ITEMS DEFAULT VITAGL GXM INVALID BOTH EMPTY)
    set(args "-DSELECTION_MODULE=${SELECTION_MODULE}")
    if (selection STREQUAL "DEFAULT")
        list(APPEND args -DEXPECTED_SELECTION=VITAGL)
    elseif (selection STREQUAL "EMPTY")
        list(APPEND args -DEXPECTED_SELECTION=EMPTY "-DAURORA_VITA_RENDERER=")
    else ()
        list(APPEND args "-DEXPECTED_SELECTION=${selection}" "-DAURORA_VITA_RENDERER=${selection}")
    endif ()
    execute_process(COMMAND "${CMAKE_COMMAND}" ${args} -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if (selection MATCHES "^(DEFAULT|VITAGL|GXM)$")
        if (NOT result EQUAL 0)
            message(FATAL_ERROR "Selection ${selection} failed: ${output}${error}")
        endif ()
    else ()
        if (result EQUAL 0 OR NOT error MATCHES "AURORA_VITA_RENDERER must be VITAGL or GXM")
            message(FATAL_ERROR "Invalid selection ${selection} was not rejected correctly: ${output}${error}")
        endif ()
    endif ()
endforeach ()
message(STATUS "PASS: default/VITAGL/GXM selection and invalid/combined/empty rejection")
