#pragma once

#include "dolphin/gx/GXEnum.h"
#include "../internal.hpp"

namespace aurora::gx::fifo {

// Reset the CP write-deduplication state whenever the GX shadow state is reinitialized.
void reset_cp_register_cache();

// Process a buffer of GX FIFO commands
void process(const uint8_t* data, uint32_t size, bool bigEndian);

// Submit already-packed direct vertex bytes against the current GX state.
bool submit_raw_draw(GXPrimitive prim, GXVtxFmt fmt, const uint8_t* vertices, uint16_t vtxCount,
                     uint32_t vertexBytes, const uint8_t* stableSource = nullptr);

#if defined(MKW_TARGET_VITA)
// Fast path for the display lists generated by Strikers: exactly one GX draw
// followed only by alignment padding. Returns false for every other list so
// GXCallDisplayList can fall back to the normal FIFO path.
bool submit_simple_display_list(const uint8_t* data, uint32_t size);
#endif

} // namespace aurora::gx::fifo
