#pragma once

#include "dolphin/gx/GXEnum.h"
#include <memory>
#include <vector>
#include "../internal.hpp"

namespace aurora::gx::fifo {

struct XfEqualPositionStats {
  uint64_t inspected=0;
  uint64_t unchanged=0;
  uint64_t changed=0;
};
// A2a: position palette XF writes only. OFF is the existing reference path.
// Configure before starting the GX worker; read statistics only after joining.
void set_xf_equal_position_writes(bool enabled) noexcept;
XfEqualPositionStats xf_equal_position_stats() noexcept;

// Reset the CP write-deduplication state whenever the GX shadow state is reinitialized.
void reset_cp_register_cache();

// Process a buffer of GX FIFO commands
void process(const uint8_t* data, uint32_t size, bool bigEndian);
#if defined(MKW_TARGET_VITA)
// An embedding runtime can execute synchronous GX processing on its native
// thread stack while retaining FIFO order and caller-owned argument lifetimes.
using SynchronousDispatch = void (*)(void (*)(void*), void*);
void set_synchronous_dispatch(SynchronousDispatch dispatch);
#endif

// Submit already-packed direct vertex bytes against the current GX state.
bool submit_raw_draw(GXPrimitive prim, GXVtxFmt fmt, const uint8_t* vertices, uint16_t vtxCount,
                     uint32_t vertexBytes, const uint8_t* stableSource = nullptr);

#if defined(MKW_TARGET_VITA)
// Fast path for the display lists generated by Strikers: exactly one GX draw
// followed only by alignment padding. It is synchronous-frontend only: while
// the async worker is active it returns false so GXCallDisplayList falls back
// to the ordered FIFO and keeps DrawSink/GXState single-owner.
bool submit_simple_display_list(const uint8_t* data, uint32_t size);
// Consumer only: preceding CP/XF/BP segments have already executed. No producer
// dirty-state access, FIFO drain, reordering or additional lifetime barrier.
void set_prepared_display_lists_enabled(bool enabled);
bool submit_prepared_display_list(const std::shared_ptr<const std::vector<uint8_t>>& bytes,
                                  uint32_t size,const uint8_t* stableSource,uint64_t immutableIdentity);
void prepared_display_list_stats(uint64_t& hits,uint64_t& misses,uint64_t& rejected);
#endif

} // namespace aurora::gx::fifo
